PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT { ?subject rdfs:subClassOf ?supertype }
WHERE {
    SELECT DISTINCT ?subject ?supertype
    WHERE {
        { ?subject a owl:Class . } UNION { ?individual a ?subject . } .
        OPTIONAL { ?subject rdfs:subClassOf ?supertype } .
        FILTER (!isBlank(?supertype)) .
        FILTER (?subject != owl:Class &&
              ?subject != rdf:List &&
              ?subject != rdf:Property &&
              ?subject != rdfs:Class &&
              ?subject != rdfs:Datatype &&
              ?subject != rdfs:ContainerMembershipProperty &&
              ?subject != owl:DatatypeProperty &&
              ?subject != owl:NamedIndividual &&
              ?subject != owl:Ontology ) .
    } ORDER BY ?subject
}