PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {{
  optional {{ <{uri}> rdfs:comment ?comment }}
  optional {{ <{uri}> rdfs:label ?label }}
  optional {{ <{uri}> rdfs:range ?range }} # kind of resource expected as the object of this prop
  optional {{ <{uri}> rdfs:domain ?domain }} # kind of resource expected as the subject of this prop
}}